/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// @ts-nocheck

import React, { useRef } from 'react'
import { useGLTF,

} from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/beach-ball/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere000.geometry} material={materials['White.008']} />
      <mesh geometry={nodes.Sphere000_1.geometry} material={materials['Blue.004']} />
      <mesh geometry={nodes.Sphere000_2.geometry} material={materials['Red.003']} />
      <mesh geometry={nodes.Sphere000_3.geometry} material={materials['Yellow.012']} />

    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/beach-ball/model.gltf')
