/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// @ts-nocheck

import { Clone, Float, useGLTF } from '@react-three/drei';

export default function Model(props) {
  const starModel = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/star/model.gltf');

  return <>
    <Float rotationIntensity={0.2}>
      <Clone
        object={starModel.scene}
        position={[4, 1, 0]} scale={0.5}
        rotation-y={0.2}
      >
      </Clone>
    </Float>


    <Float rotationIntensity={0.2}>
      <Clone
        object={starModel.scene}
        position={[3, 2, 0]} scale={0.5}
        rotation-y={-0.1}
      >
      </Clone>
    </Float>

    <Float rotationIntensity={0.2}>
      <Clone
        object={starModel.scene}
        position={[3.5, 0, 0]} scale={0.5}
        rotation-y={0.2}
      >
      </Clone>
    </Float>


    <Float rotationIntensity={0.2}>
      <Clone
        object={starModel.scene}
        position={[3, -1, 0]} scale={0.5}
        rotation-y={0.2}
      >
      </Clone>
    </Float>
  </>
}
